"""Bake the speech-line glyph subset of Noto Sans JP into triangle meshes.

Only the code points used by the localized speech catalog are baked, so the
game never ships the full CJK font. The outline flattening and nonzero
trapezoid triangulation are shared with tools/bake_vector_font.py.
"""
import argparse
import hashlib
import json
import re
import sys
from pathlib import Path


def load_catalog(path):
    catalog = json.loads(path.read_text(encoding="utf-8"))
    lines = catalog["lines"]
    keys = [line["key"] for line in lines]
    if not lines or len(set(keys)) != len(keys):
        raise ValueError("speech catalog needs unique, non-empty line keys")
    for line in lines:
        if not line["key"] or not line["text"]:
            raise ValueError("speech catalog lines need a key and a text")
    return catalog["locale"], lines


def c_bytes(text):
    # Escape every byte so the generated file is ASCII and no hex escape can
    # swallow a following character.
    return '"' + "".join("\\x%02X" % b for b in text.encode("utf-8")) + '"'


def catalog_codepoints(lines):
    return sorted({ord(ch) for line in lines for ch in line["text"]})


def read_baked_header(inc_text):
    """Return (catalog SHA-256, baked code points) recorded in a generated file."""
    catalog = re.search(r"^// Catalog SHA-256: ([0-9a-f]{64})$", inc_text, re.M)
    ranges = inc_text.split("kSpeechGlyphRanges[] = {", 1)[1].split("};", 1)[0]
    codepoints = [int(value, 16) for value in re.findall(r"^\{0x([0-9A-F]+),", ranges, re.M)]
    return (catalog.group(1) if catalog else None), codepoints


def main():
    # fontTools is only needed to bake; the helpers above stay importable
    # without it so the repository tests can check the generated file.
    from fontTools.ttLib import TTFont
    from fontTools.varLib.instancer import instantiateVariableFont
    sys.path.insert(0, str(Path(__file__).resolve().parent))
    from bake_vector_font import ContourPen, triangulate

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--font", type=Path, required=True)
    parser.add_argument("--catalog", type=Path, required=True)
    parser.add_argument("--source", type=Path, required=True,
                        help="data/fonts/NotoSansJP/source.json")
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()

    font_bytes = args.font.read_bytes()
    font_sha = hashlib.sha256(font_bytes).hexdigest()
    source = json.loads(args.source.read_text(encoding="utf-8"))
    expected = next(f["sha256"] for f in source["files"] if f["file"].endswith(".ttf"))
    if font_sha != expected:
        raise ValueError("font SHA-256 does not match source.json")

    locale, lines = load_catalog(args.catalog)
    codepoints = catalog_codepoints(lines)

    font = TTFont(args.font)
    if "fvar" in font:
        font = instantiateVariableFont(font, {"wght": 500}, inplace=False)
    glyphs, cmap = font.getGlyphSet(), font.getBestCmap()
    em = font["head"].unitsPerEm
    vertices, indices, entries = [], [], []
    for codepoint in codepoints:
        if codepoint not in cmap:
            raise ValueError("font has no glyph for U+%04X" % codepoint)
        name = cmap[codepoint]
        pen = ContourPen(glyphs, em / 512)
        glyphs[name].draw(pen)
        # Normalized to the em square: x = 4096 per em, y = 4096 at the
        # baseline and decreasing upward (the vector font convention).
        points, triangles = triangulate(pen.contours, em)
        advance = font["hmtx"][name][0] / em
        entries.append((codepoint, len(vertices), len(points), len(indices),
                        len(triangles), advance))
        vertices.extend(points)
        indices.extend(triangles)
    if len(vertices) >= 65536:
        raise ValueError("speech glyph subset exceeds 16-bit point indices")

    catalog_sha = hashlib.sha256(args.catalog.read_bytes()).hexdigest()
    out = [
        "// Generated by tools/bake_speech_glyphs.py. Noto Sans JP, OFL-1.1.",
        "// Font SHA-256: " + font_sha,
        "// Catalog SHA-256: " + catalog_sha,
        'constexpr const char* kSpeechLocale = "%s";' % locale,
        "constexpr SpeechGlyphPoint kSpeechGlyphPoints[] = {",
    ]
    out += ["{%d,%d}," % p for p in vertices]
    out += ["};", "constexpr std::uint16_t kSpeechGlyphIndices[] = {"]
    out += [",".join(map(str, indices[i:i + 30])) + "," for i in range(0, len(indices), 30)]
    out += ["};", "constexpr SpeechGlyphRange kSpeechGlyphRanges[] = {"]
    out += ["{0x%04X,%d,%d,%d,%d,%.9fF}," % entry for entry in entries]
    out += ["};", "constexpr SpeechLineEntry kSpeechLineEntries[] = {"]
    out += ["{%s,%s}," % (c_bytes(line["key"]), c_bytes(line["text"])) for line in lines]
    out += ["};", ""]
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text("\n".join(out), encoding="utf-8", newline="\n")
    print(json.dumps({"glyphs": len(entries), "vertices": len(vertices),
                      "triangles": len(indices) // 3, "lines": len(lines),
                      "fontSha256": font_sha}))


if __name__ == "__main__":
    main()
