"""Bake Google Fonts outlines into triangle meshes; no raster font atlas."""
import argparse
import hashlib
import json
from pathlib import Path
from fontTools.ttLib import TTFont
from fontTools.varLib.instancer import instantiateVariableFont
from fontTools.pens.basePen import BasePen


class ContourPen(BasePen):
    def __init__(self, glyphs, tolerance):
        super().__init__(glyphs)
        self.contours = []
        self.tolerance = tolerance

    def _moveTo(self, p):
        self.contours.append([p])

    def _lineTo(self, p):
        self.contours[-1].append(p)

    def _closePath(self):
        if self.contours[-1][-1] != self.contours[-1][0]:
            self.contours[-1].append(self.contours[-1][0])

    def _endPath(self):
        self._closePath()

    def _qCurveToOne(self, control, end):
        def split(start, middle, finish, depth=0):
            error = max(abs(start[i]-2*middle[i]+finish[i]) for i in (0, 1))
            if error <= self.tolerance*4 or depth >= 16:
                self._lineTo(finish)
                return
            left = tuple((start[i]+middle[i])*0.5 for i in (0, 1))
            right = tuple((middle[i]+finish[i])*0.5 for i in (0, 1))
            center = tuple((left[i]+right[i])*0.5 for i in (0, 1))
            split(start, left, center, depth+1)
            split(center, right, finish, depth+1)
        split(self._getCurrentPoint(), control, end)

    def _curveToOne(self, c1, c2, end):
        raise ValueError("this reproducible bake expects TrueType quadratic outlines")


def triangulate(contours, cap_height):
    # Sweep outline vertex heights. Nonzero winding retains counters (B/O/8)
    # and nested contours; each filled interval becomes a vector trapezoid.
    edges = [(a, b) for contour in contours for a, b in zip(contour, contour[1:]) if a[1] != b[1]]
    levels = sorted({p[1] for contour in contours for p in contour})
    points, triangles, lookup = [], [], {}
    def point(p):
        value = (round(p[0]/cap_height*4096), round((1-p[1]/cap_height)*4096))
        if value not in lookup:
            lookup[value] = len(points)
            points.append(value)
        return lookup[value]
    def at(edge, y):
        a, b = edge
        return a[0] + (b[0]-a[0])*(y-a[1])/(b[1]-a[1])
    for bottom, top in zip(levels, levels[1:]):
        middle = (bottom+top)*0.5
        active = [e for e in edges if min(e[0][1], e[1][1]) < middle < max(e[0][1], e[1][1])]
        active.sort(key=lambda e: at(e, middle))
        winding, left = 0, None
        for edge in active:
            previous = winding
            winding += 1 if edge[1][1] > edge[0][1] else -1
            if previous == 0 and winding != 0:
                left = edge
            elif previous != 0 and winding == 0:
                quad = [(at(left,bottom),bottom),(at(edge,bottom),bottom),
                        (at(edge,top),top),(at(left,top),top)]
                indices = [point(p) for p in quad]
                for tri in ((indices[0],indices[1],indices[2]),(indices[0],indices[2],indices[3])):
                    a,b,c = [points[i] for i in tri]
                    area = (b[0]-a[0])*(c[1]-a[1])-(b[1]-a[1])*(c[0]-a[0])
                    if area:
                        triangles.extend(tri if area > 0 else (tri[0],tri[2],tri[1]))
        if winding:
            raise ValueError("glyph contour is not closed")
    if len(points) >= 65536:
        raise ValueError("glyph exceeds 16-bit mesh indices")
    return points, triangles


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--font", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    font = TTFont(args.font)
    if "fvar" in font:
        font = instantiateVariableFont(font, {"wght": 500}, inplace=False)
    glyphs, cmap = font.getGlyphSet(), font.getBestCmap()
    cap = font["OS/2"].sCapHeight
    vertices, indices, entries = [], [], []
    for codepoint in range(32, 127):
        name = cmap[codepoint]
        pen = ContourPen(glyphs, cap/512)
        glyphs[name].draw(pen)
        points, triangles = triangulate(pen.contours, cap)
        advance = font["hmtx"][name][0]/cap
        entries.append((len(vertices),len(points),len(indices),len(triangles),advance))
        vertices.extend(points)
        indices.extend(triangles)
    lines = ["// Generated by tools/bake_vector_font.py. Roboto Mono, OFL-1.1.",
             "// Source SHA-256: "+hashlib.sha256(args.font.read_bytes()).hexdigest(),
             "constexpr VectorFontPoint kFontPoints[] = {"]
    lines += ["{%d,%d}," % p for p in vertices]
    lines += ["};", "constexpr std::uint16_t kFontIndices[] = {"]
    lines += [",".join(map(str,indices[i:i+30]))+"," for i in range(0,len(indices),30)]
    lines += ["};", "constexpr GlyphRange kFontGlyphs[] = {"]
    lines += ["{%d,%d,%d,%d,%.9fF}," % entry for entry in entries]
    lines += ["};",""]
    args.output.parent.mkdir(parents=True,exist_ok=True)
    args.output.write_text("\n".join(lines),encoding="utf-8")
    print(json.dumps({"glyphs":len(entries),"vertices":len(vertices),"triangles":len(indices)//3,
                      "fontSha256":hashlib.sha256(args.font.read_bytes()).hexdigest()}))


if __name__ == "__main__":
    main()
