# Host shader compilation and target Vulkan linking are separate.
find_program(KONBINI_HOST_GLSLC NAMES glslc HINTS "$ENV{VULKAN_SDK}/Bin" "$ENV{VULKAN_SDK}/bin" NO_CMAKE_FIND_ROOT_PATH REQUIRED)
if(NOT TARGET Vulkan::glslc)
  add_executable(Vulkan::glslc IMPORTED GLOBAL)
  set_target_properties(Vulkan::glslc PROPERTIES IMPORTED_LOCATION "${KONBINI_HOST_GLSLC}")
endif()
list(PREPEND CMAKE_MODULE_PATH "${CMAKE_CURRENT_LIST_DIR}/mobile")
set(Vulkan_FOUND TRUE)
if(ANDROID)
  add_library(Vulkan::Vulkan INTERFACE IMPORTED GLOBAL)
  set_property(TARGET Vulkan::Vulkan PROPERTY INTERFACE_LINK_LIBRARIES vulkan)
  set(Vulkan_LIBRARIES vulkan)
else()
  if(NOT EXISTS "${KONBINI_MOLTENVK_LIBRARY}" OR NOT EXISTS "${KONBINI_VULKAN_HEADERS}/vulkan/vulkan.h")
    message(FATAL_ERROR "iOS requires KONBINI_MOLTENVK_LIBRARY and KONBINI_VULKAN_HEADERS for the selected device/simulator SDK")
  endif()
  add_library(Vulkan::Vulkan UNKNOWN IMPORTED GLOBAL)
  set_target_properties(Vulkan::Vulkan PROPERTIES
    IMPORTED_LOCATION "${KONBINI_MOLTENVK_LIBRARY}"
    INTERFACE_INCLUDE_DIRECTORIES "${KONBINI_VULKAN_HEADERS}")
  set(Vulkan_LIBRARIES Vulkan::Vulkan)
  set(Vulkan_INCLUDE_DIRS "${KONBINI_VULKAN_HEADERS}")
  add_compile_definitions(KONBINI_PLATFORM_IOS=1)
endif()
